import type { Equipment } from "@/types/equipment";

export const data: Equipment[] = [
  {
    no: 1,
    equipmentName: "Cẩu trục 10 tấn",
    equipmentCode: "B20100921",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đôi", level4: "10T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Line 1", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "10T", produceYear: 2020 },
    specification: "Khẩu độ 18m, chiều cao nâng 9m", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 2,
    equipmentName: "Cẩu trục 15 tấn",
    equipmentCode: "B20101028",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đơn", level4: "15T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Line 1", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "15T", produceYear: 2020 },
    specification: "Khẩu độ 24m, chiều cao nâng 12m", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 3,
    equipmentName: "Cẩu trục 15 tấn",
    equipmentCode: "B20101029",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đơn", level4: "15T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Line 1", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "15T", produceYear: 2020 },
    specification: "Khẩu độ 24m, chiều cao nâng 12m", installationLocation: "VT", note: "", status: "maintenance",
  },
  {
    no: 4,
    equipmentName: "Cẩu trục 15 tấn",
    equipmentCode: "B20101030",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đơn", level4: "15T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Line 2", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "15T", produceYear: 2020 },
    specification: "Khẩu độ 24m, chiều cao nâng 12m", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 5,
    equipmentName: "Cẩu trục 15 tấn",
    equipmentCode: "B20101031",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đơn", level4: "15T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Line 2", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "15T", produceYear: 2021 },
    specification: "Khẩu độ 24m, chiều cao nâng 12m", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 6,
    equipmentName: "Cẩu trục 15 tấn",
    equipmentCode: "B20101032",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đơn", level4: "15T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Line 3", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "15T", produceYear: 2021 },
    specification: "Khẩu độ 24m, chiều cao nâng 12m", installationLocation: "VT", note: "", status: "inspection",
  },
  {
    no: 7,
    equipmentName: "Máy hàn MIG 500A",
    equipmentCode: "C21050101",
    equipmentGroup: { level1: "2. THIẾT BỊ HÀN", level2: "2.1. Máy hàn MIG/MAG", level3: "MIG", level4: "500A" },
    organization: { legalEntity: "A07", factory: "HÀ NỘI", workshop: "Hàn", layout: "Line A", workCenter: "WC-HAN-01", area: "" },
    manufacturer: { country: "NHẬT BẢN", brand: "Lincoln Electric", model: "Power MIG 500", produceYear: 2019 },
    specification: "Điện áp 380V, dòng hàn max 500A, tần số 50Hz", installationLocation: "HN", note: "", status: "active",
  },
  {
    no: 8,
    equipmentName: "Máy hàn MIG 350A",
    equipmentCode: "C21050102",
    equipmentGroup: { level1: "2. THIẾT BỊ HÀN", level2: "2.1. Máy hàn MIG/MAG", level3: "MAG", level4: "350A" },
    organization: { legalEntity: "A07", factory: "HÀ NỘI", workshop: "Hàn", layout: "Line A", workCenter: "WC-HAN-01", area: "" },
    manufacturer: { country: "NHẬT BẢN", brand: "Lincoln Electric", model: "Power MIG 350", produceYear: 2019 },
    specification: "Điện áp 380V, dòng hàn max 350A", installationLocation: "HN", note: "", status: "active",
  },
  {
    no: 9,
    equipmentName: "Máy hàn TIG 200A",
    equipmentCode: "C21050103",
    equipmentGroup: { level1: "2. THIẾT BỊ HÀN", level2: "2.2. Máy hàn TIG", level3: "TIG", level4: "200A" },
    organization: { legalEntity: "A07", factory: "HÀ NỘI", workshop: "Hàn", layout: "Line B", workCenter: "WC-HAN-02", area: "" },
    manufacturer: { country: "ĐỨC", brand: "Miller Electric", model: "Dynasty 200", produceYear: 2020 },
    specification: "Điện áp 220V, dòng hàn max 200A, làm mát nước", installationLocation: "HN", note: "", status: "maintenance",
  },
  {
    no: 10,
    equipmentName: "Máy cắt Plasma CNC",
    equipmentCode: "C21060201",
    equipmentGroup: { level1: "3. THIẾT BỊ GIA CÔNG CẮT", level2: "3.1. Máy cắt Plasma", level3: "CNC", level4: "Plasma" },
    organization: { legalEntity: "A07", factory: "HÀ NỘI", workshop: "Cắt", layout: "Line C", workCenter: "WC-CAT-01", area: "" },
    manufacturer: { country: "MỸ", brand: "Hypertherm", model: "XPR300", produceYear: 2021 },
    specification: "Công suất 300A, cắt thép dày max 80mm", installationLocation: "HN", note: "", status: "active",
  },
  {
    no: 11,
    equipmentName: "Máy cắt Laser 6kW",
    equipmentCode: "C21060301",
    equipmentGroup: { level1: "3. THIẾT BỊ GIA CÔNG CẮT", level2: "3.2. Máy cắt Laser", level3: "Fiber Laser", level4: "6kW" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Laser", layout: "Bay 1", workCenter: "WC-LASER-01", area: "" },
    manufacturer: { country: "TRUNG QUỐC", brand: "Trumpf", model: "TruLaser 3030", produceYear: 2022 },
    specification: "Công suất 6000W, bàn làm việc 3000x1500mm", installationLocation: "HCM", note: "", status: "active",
  },
  {
    no: 12,
    equipmentName: "Máy cắt Laser 3kW",
    equipmentCode: "C21060302",
    equipmentGroup: { level1: "3. THIẾT BỊ GIA CÔNG CẮT", level2: "3.2. Máy cắt Laser", level3: "Fiber Laser", level4: "3kW" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Laser", layout: "Bay 1", workCenter: "WC-LASER-01", area: "" },
    manufacturer: { country: "TRUNG QUỐC", brand: "Bystronic", model: "ByStar 3015", produceYear: 2022 },
    specification: "Công suất 3000W, bàn làm việc 3000x1500mm", installationLocation: "HCM", note: "", status: "active",
  },
  {
    no: 13,
    equipmentName: "Máy tiện CNC",
    equipmentCode: "D22010401",
    equipmentGroup: { level1: "4. THIẾT BỊ GIA CÔNG CƠ KHÍ", level2: "4.1. Máy tiện", level3: "CNC", level4: "Tiện" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Cơ khí", layout: "Bay 2", workCenter: "WC-CK-01", area: "" },
    manufacturer: { country: "ĐÀI LOAN", brand: "Mazak", model: "Quick Turn 250", produceYear: 2018 },
    specification: "Đường kính quay max Ø500mm, chiều dài 1000mm", installationLocation: "HCM", note: "", status: "active",
  },
  {
    no: 14,
    equipmentName: "Máy phay CNC 3 trục",
    equipmentCode: "D22010501",
    equipmentGroup: { level1: "4. THIẾT BỊ GIA CÔNG CƠ KHÍ", level2: "4.2. Máy phay", level3: "CNC 3 trục", level4: "Phay" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Cơ khí", layout: "Bay 2", workCenter: "WC-CK-02", area: "" },
    manufacturer: { country: "ĐÀI LOAN", brand: "Haas", model: "VF-2SS", produceYear: 2019 },
    specification: "Hành trình X/Y/Z: 762/406/508mm, trục chính 12000 rpm", installationLocation: "HCM", note: "", status: "inspection",
  },
  {
    no: 15,
    equipmentName: "Máy phay CNC 5 trục",
    equipmentCode: "D22010502",
    equipmentGroup: { level1: "4. THIẾT BỊ GIA CÔNG CƠ KHÍ", level2: "4.2. Máy phay", level3: "CNC 5 trục", level4: "Phay" },
    organization: { legalEntity: "A09", factory: "ĐÀ NẴNG", workshop: "Gia công", layout: "Line 1", workCenter: "WC-GC-01", area: "" },
    manufacturer: { country: "ĐỨC", brand: "DMG Mori", model: "DMU 50", produceYear: 2021 },
    specification: "Hành trình X/Y/Z: 500/450/400mm, trục chính 18000 rpm", installationLocation: "DN", note: "", status: "active",
  },
  {
    no: 16,
    equipmentName: "Robot hàn tự động",
    equipmentCode: "E22020601",
    equipmentGroup: { level1: "5. ROBOT CÔNG NGHIỆP", level2: "5.1. Robot hàn", level3: "Robot hàn MIG", level4: "Auto" },
    organization: { legalEntity: "A09", factory: "ĐÀ NẴNG", workshop: "Robot", layout: "Line 2", workCenter: "WC-ROBOT-01", area: "" },
    manufacturer: { country: "NHẬT BẢN", brand: "FANUC", model: "ArcMate 100iD", produceYear: 2022 },
    specification: "Tải trọng 12kg, tầm với 1636mm, 6 bậc tự do", installationLocation: "DN", note: "", status: "active",
  },
  {
    no: 17,
    equipmentName: "Robot hàn spot",
    equipmentCode: "E22020602",
    equipmentGroup: { level1: "5. ROBOT CÔNG NGHIỆP", level2: "5.2. Robot hàn điểm", level3: "Spot Welding", level4: "Auto" },
    organization: { legalEntity: "A09", factory: "ĐÀ NẴNG", workshop: "Robot", layout: "Line 2", workCenter: "WC-ROBOT-01", area: "" },
    manufacturer: { country: "NHẬT BẢN", brand: "Yaskawa", model: "MA2010", produceYear: 2022 },
    specification: "Tải trọng 10kg, tầm với 1730mm, IP67", installationLocation: "DN", note: "", status: "maintenance",
  },
  {
    no: 18,
    equipmentName: "Xe nâng điện 3 tấn",
    equipmentCode: "F22030701",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.2. Xe nâng", level3: "Xe nâng điện", level4: "3T" },
    organization: { legalEntity: "A09", factory: "ĐÀ NẴNG", workshop: "Logistics", layout: "Kho A", workCenter: "WC-KHOVT-01", area: "" },
    manufacturer: { country: "HÀN QUỐC", brand: "Hyster", model: "J3.0XN", produceYear: 2020 },
    specification: "Tải trọng 3000kg, nâng cao 4500mm, pin 48V/600Ah", installationLocation: "DN", note: "", status: "active",
  },
  {
    no: 19,
    equipmentName: "Xe nâng dầu 5 tấn",
    equipmentCode: "F22030702",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.2. Xe nâng", level3: "Xe nâng dầu", level4: "5T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "Logistics", layout: "Kho B", workCenter: "WC-KHOVT-02", area: "" },
    manufacturer: { country: "HÀN QUỐC", brand: "Komatsu", model: "FD50T-17", produceYear: 2019 },
    specification: "Tải trọng 5000kg, nâng cao 3000mm, động cơ Diesel", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 20,
    equipmentName: "Máy nén khí 75kW",
    equipmentCode: "G22040801",
    equipmentGroup: { level1: "6. THIẾT BỊ KHÍ NÉN", level2: "6.1. Máy nén khí trục vít", level3: "Trục vít", level4: "75kW" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "Tiện ích", layout: "Trạm khí nén", workCenter: "WC-UTILITY-01", area: "" },
    manufacturer: { country: "ĐỨC", brand: "Atlas Copco", model: "GA75+", produceYear: 2018 },
    specification: "Công suất 75kW, lưu lượng 12.9 m³/min, áp suất 10 bar", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 21,
    equipmentName: "Máy nén khí 55kW",
    equipmentCode: "G22040802",
    equipmentGroup: { level1: "6. THIẾT BỊ KHÍ NÉN", level2: "6.1. Máy nén khí trục vít", level3: "Trục vít", level4: "55kW" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Tiện ích", layout: "Trạm khí nén", workCenter: "WC-UTILITY-02", area: "" },
    manufacturer: { country: "ĐỨC", brand: "Atlas Copco", model: "GA55+", produceYear: 2019 },
    specification: "Công suất 55kW, lưu lượng 9.4 m³/min, áp suất 8 bar", installationLocation: "HCM", note: "", status: "inactive",
  },
  {
    no: 22,
    equipmentName: "Cổng trục 20 tấn",
    equipmentCode: "B22050922",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.3. Cổng trục", level3: "Cổng trục chạy ray", level4: "20T" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "SC", layout: "Yard A", workCenter: "SC", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "VINACRANES", model: "GC20T", produceYear: 2021 },
    specification: "Khẩu độ 30m, chiều cao nâng 15m, tải 20T", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 23,
    equipmentName: "Máy bơm nước công nghiệp",
    equipmentCode: "H22060901",
    equipmentGroup: { level1: "7. THIẾT BỊ THỦY LỰC & KHÍ NÉN", level2: "7.1. Máy bơm", level3: "Bơm ly tâm", level4: "Công nghiệp" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Tiện ích", layout: "Trạm bơm", workCenter: "WC-UTILITY-02", area: "" },
    manufacturer: { country: "ĐỨC", brand: "Grundfos", model: "CR45-3", produceYear: 2020 },
    specification: "Lưu lượng 45 m³/h, cột áp 30m, công suất 7.5kW", installationLocation: "HCM", note: "", status: "active",
  },
  {
    no: 24,
    equipmentName: "Máy kiểm tra siêu âm UT",
    equipmentCode: "I22071001",
    equipmentGroup: { level1: "8. THIẾT BỊ KIỂM TRA", level2: "8.1. Kiểm tra không phá hủy", level3: "UT", level4: "NDT" },
    organization: { legalEntity: "A09", factory: "ĐÀ NẴNG", workshop: "QC", layout: "Phòng NDT", workCenter: "WC-QC-01", area: "" },
    manufacturer: { country: "MỸ", brand: "GE Inspection", model: "USM 36", produceYear: 2020 },
    specification: "Tần số 0.5-20MHz, màn hình TFT 8.4 inch màu", installationLocation: "DN", note: "", status: "active",
  },
  {
    no: 25,
    equipmentName: "Máy đo CMM 3D",
    equipmentCode: "I22071002",
    equipmentGroup: { level1: "8. THIẾT BỊ KIỂM TRA", level2: "8.2. Đo lường 3D", level3: "CMM", level4: "3D" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "QC", layout: "Phòng đo", workCenter: "WC-QC-02", area: "" },
    manufacturer: { country: "ĐỨC", brand: "Zeiss", model: "Contura G2 RDS", produceYear: 2021 },
    specification: "Vùng đo 1000x700x600mm, độ chính xác 1.7+3L/1000 μm", installationLocation: "HCM", note: "", status: "active",
  },
  {
    no: 26,
    equipmentName: "Lò nhiệt luyện buồng",
    equipmentCode: "J22081101",
    equipmentGroup: { level1: "9. THIẾT BỊ NHIỆT LUYỆN", level2: "9.1. Lò buồng", level3: "Lò điện trở", level4: "Nhiệt luyện" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "Nhiệt luyện", layout: "Xưởng NL", workCenter: "WC-NL-01", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "Nabertherm", model: "N 250/85HA", produceYear: 2019 },
    specification: "Nhiệt độ tối đa 850°C, thể tích buồng 250L", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 27,
    equipmentName: "Băng tải lắp ráp tự động",
    equipmentCode: "K22091201",
    equipmentGroup: { level1: "10. THIẾT BỊ VẬN CHUYỂN", level2: "10.1. Băng tải", level3: "Băng tải điện", level4: "Lắp ráp" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Lắp ráp", layout: "Line LA-01", workCenter: "WC-LA-01", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "Hà Thành", model: "BT-1200", produceYear: 2022 },
    specification: "Chiều rộng 1200mm, chiều dài 50m, tốc độ 0-15 m/min", installationLocation: "HCM", note: "", status: "active",
  },
  {
    no: 28,
    equipmentName: "Máy sơn phun tĩnh điện",
    equipmentCode: "L22101301",
    equipmentGroup: { level1: "11. THIẾT BỊ SƠN", level2: "11.1. Sơn tĩnh điện", level3: "Phun tĩnh điện", level4: "Powder Coating" },
    organization: { legalEntity: "A09", factory: "ĐÀ NẴNG", workshop: "Sơn", layout: "Buồng sơn 1", workCenter: "WC-SON-01", area: "" },
    manufacturer: { country: "ĐỨC", brand: "Wagner", model: "PEM X1", produceYear: 2020 },
    specification: "Điện áp phun 0-100kV, lưu lượng bột 0-600g/min", installationLocation: "DN", note: "", status: "active",
  },
  {
    no: 29,
    equipmentName: "Máy hàn SAW tự động",
    equipmentCode: "C23010103",
    equipmentGroup: { level1: "2. THIẾT BỊ HÀN", level2: "2.3. Máy hàn SAW", level3: "Hàn dưới thuốc", level4: "Auto" },
    organization: { legalEntity: "A07", factory: "VŨNG TÀU", workshop: "Hàn", layout: "Line D", workCenter: "WC-HAN-03", area: "" },
    manufacturer: { country: "THỤY ĐIỂN", brand: "ESAB", model: "A6 SAW", produceYear: 2023 },
    specification: "Dòng hàn max 1000A, điện áp 36-44V, tốc độ 0.1-3 m/min", installationLocation: "VT", note: "", status: "active",
  },
  {
    no: 30,
    equipmentName: "Cẩu trục 5 tấn",
    equipmentCode: "B23020923",
    equipmentGroup: { level1: "1. THIẾT BỊ NÂNG HẠ", level2: "1.1. Cầu trục", level3: "Dầm đơn", level4: "5T" },
    organization: { legalEntity: "A08", factory: "HỒ CHÍ MINH", workshop: "Lắp ráp", layout: "Bay 3", workCenter: "WC-LA-02", area: "" },
    manufacturer: { country: "VIỆT NAM", brand: "DDC", model: "5T", produceYear: 2023 },
    specification: "Khẩu độ 12m, chiều cao nâng 6m, tải 5T", installationLocation: "HCM", note: "", status: "active",
  },
];
